### ISSUE TITLE
Is it possible to turn off the SNMP poller ?

### ISSUE THREAD

**Issue by chirayu-patel** [akvorado/akvorado#1155]
I have recently started setting up akvorado . The way I understand is, akvorado expects the interface index and in response, akvorado  will make SNMP request to the router to get the interface name from the index.

Is it possible to turn off the snmp poller and somehow mention the interface name from config or somewhere if need is to enrich the data.

**Comment by fischerdouglas** [comment]
I'm going to comment on a hypothesis that has crossed my mind in the past...
I gave up on the idea because I don't know how to program, and because time was short.

And I'm already saying that my crazy idea doesn't solve this issue here at Akvorado...
But perhaps it can serve as an inspiration to others.

The idea was to create a kind of "router-faker-tool".
Maybe similar to what kproxy does, but with an adaptive LIE layer in the way.
A "thing" that:
- Had a base for transforming "Original IDs -> Figurative IDs" of the interfaces, including SNMP OID, and descriptions.
- Receive the Flows, replace the IDs according to the transformation basis, and resend.
- That there would be an SNMP agent to respond to GETs from the Servers, with the same information as the transformation base.

Yep... I know! It's an ugly idea!

**Comment by vincentbernat** [comment]
This is already possible to use gNMI or static definitions (see https://demo.akvorado.net/docs/configuration#metadata). Next version also includes the ability to fetch data from remote sources (see #1037).
