### ISSUE TITLE
NAT fields support for IPFIX

### ISSUE THREAD

**Issue by pkomissarov** [akvorado/akvorado#211]
If for example firewall on the border of a private network performs nat/masquerade, then the returning traffic should be unNATed, and destination private IP address placed in IPFIX field postNATDestinationIPv4Address. It would be great to have possibility to choose this field as a dimension and as a filter. Then it's possible to answer very popular question: who (which private IP) downloaded most of all in last X minutes and view more details if using this IP in a filter.

**Comment by vincentbernat** [comment]
I may do that at the same time than #218. I don't do that right now because maybe I need to rethink if adding many fields for everybody is really efficient. In ClickHouse, it should not take much space when unused, but the protobuf buffers may become big. But I am OK with the principle of exposing this field.

**Comment by shafiev** [comment]
@vincentbernat How i can help to you to do this?

**Comment by vincentbernat** [comment]
My plan is the following:
1. Rewrite ClickHouse migrations to not have to write a lot of code each time I add a column.
2. Add a way to specify additional fields to be collected and their mapping to ClickHouse (this also implies a dynamic protobuf schema)
3. Wire these additional fields in the console

My reasoning is that because there are many fields available in IPFIX/sFlow, hard-coding all of them will impact performance of people not using them.

Non-concerns:
- with Protobuf v3, fields with default values take 0 space
- ClickHouse should be OK with many columns

If I fail to deliver these steps in a timely manner (in two months?), I'll add them as other fields and wait for the next request.

**Comment by vincentbernat** [comment]
So, this is implemented as a disabled column. You would need a `schema.enabled` setting to add it properly. If you want to try, once the build is done, you can use `ghcr.io/akvorado/akvorado:main`. There are a lot of changes in this release, so it's preferable to not do that on your production server if you care about the data.
