### ISSUE TITLE
Add ipnetdb based asn lookup

### ISSUE THREAD

**Issue by smallsam** [akvorado/akvorado#455]
To reduce friction for new users, we can add the permissively licensed (and higher quality) data from https://ipnetdb.com/ instead of relying on maxmind's DB/registration-wall. 

It may be possible to use the https://github.com/meeb/ipnetdb-service container as a sidecar to read the mmdb directly (as this container already handles mmdb updates) or use the http service. Unfortunately the field names do not match the maxmind mmdb but otherwise it should be a simple addition.

If this proves successful, it would be interesting to determine if this data source is high enough quality to replace github.com/vincentbernat/asn2org

**Comment by vincentbernat** [comment]
Yes, this looks like a good idea. I would favor a drop-in replacement in the current architecture (the Docker container for updating Maxmind's mmdb can likely be replaced with a simple shell script). As for the field names, I suppose we can detect them when loading the database.

**Comment by vincentbernat** [comment]
There is also ipinfo.io: https://ipinfo.io/products/free-ip-database. The database is released as CC-BY-SA 4.0 and a single database includes both countries and ASN, so it could also enable us to get both information with a single lookup.

**Comment by abdullahdevrel** [comment]
I am the DevRel of IPinfo. Please let me if you have any questions.

You can check the Schema and the samples from this repo: https://github.com/ipinfo/sample-database/tree/main/IP%20to%20Country%20ASN

Or you can visit our documentation portal as well: https://ipinfo.io/developers/ip-to-country-asn-database

The data is updated daily with full accuracy coverage and it is a single database containing both IPv4 and IPv6 addresses. Comes in three different formats: CSV, MMDB, and JSON. We follow a flat tabular structure for the database and we don't have a nested data structure.


![image](https://user-images.githubusercontent.com/111275753/222691546-0d4b0ea0-3799-45b9-9c3d-f69bbf02a925.png)

**Comment by vincentbernat** [comment]
For this one, I am mostly waiting on https://github.com/oschwald/maxminddb-golang/pull/91 to not introduce a performance impact by looking up at non-existing fields.

**Comment by abdullahdevrel** [comment]
Hi @vincentbernat, Were you able to take a look at IPinfo's IP to Country ASN database? I am not very familiar with Golang, but I explored your code a bit.

Since IPinfo's database is shared with CC-BY-SA 4.0 License, users do not have to provide their own token. This eliminates the need to supply a token via the [Docker environment variable declaration](https://github.com/akvorado/akvorado/blob/main/console/data/docs/00-intro.md#quick-start). You can include your token with the repository. 

Also, the nested data structure of your existing IP geolocation database requires you to declare error catch statements for individual data queries, whereas our database is flat. You can still utilize the Golang MMDB reader. Here is an example code:

```go
package main

import (
	"fmt"
	"log"
	"net"

	"github.com/oschwald/maxminddb-golang"
)

func main() {
	db, err := maxminddb.Open("./country_asn.mmdb")
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()

	var record struct {
		Country        string `maxminddb:"country"`
		Country_Name   string `maxminddb:"country_name"`
		Continent      string `maxminddb:"continent"`
		Continent_Name string `maxminddb:"continent_name"`
		ASN            string `maxminddb:"asn"`
		AS_Name        string `maxminddb:"as_name"`
		AS_Domain      string `maxminddb:"as_domain"`
	}

	// Replace with the IP address you want to lookup
	ipAddress := "172.229.209.194"

	err = db.Lookup(net.ParseIP(ipAddress), &record)
	if err != nil {
		log.Fatal(err)
	}

	// Print the results.
	fmt.Println("Country: ", record.Country)               // Country:  US
	fmt.Println("Country Name: ", record.Country_Name)     // Country Name:  United States
	fmt.Println("Continent: ", record.Continent)           // Continent:  NA
	fmt.Println("Continent Name: ", record.Continent_Name) // Continent Name:  North America
	fmt.Println("ASN: ", record.ASN)                       // ASN:  AS15169
	fmt.Println("AS Name: ", record.AS_Name)               // AS Name:  Google LLC
	fmt.Println("AS Domain: ", record.AS_Domain)           // AS Domain:  google.com
}
```

**Comment by vincentbernat** [comment]
As stated in the previous comment, I want to avoid a performance hit by looking at different fields depending on the database used (reflection is expensive).

**Comment by abdullahdevrel** [comment]
Hey @vincentbernat sorry about that. It is because of the database download rate limit. 

The rate limit policy is that unique IP address x unique token x unique download database id. Currently, we have a rate limit of 3 downloads per token per IP address. If you use the access token in the docker image, you will get 3 more downloads. You can use any IPinfo token you want.

https://community.ipinfo.io/t/announcement-we-are-adding-rate-limits-to-data-downloads/358

I will take a look to see if I can somehow increase your rate limit for your particular token. My apologies for the inconvenience.

**Comment by vincentbernat** [comment]
Ack. Maybe this is good enough. With the update to the Docker image, hitting the limit shouldn't delete the current database as it was before, so the limit should be OK for most people.

**Comment by abdullahdevrel** [comment]
Hey @vincentbernat We have increased the rate limit on your current access token to 10. I think another option could be to keep your token as a secret development token and use our docker image token as the production token for the project. Let me know what you think. I can create a new token for your account with a higher rate limit and email it to you.

By the way, when you have the time, can you please update the [README.md](https://github.com/akvorado/akvorado/blob/main/README.md?plain=1#L4)?

**Comment by vincentbernat** [comment]
The token is not used for CI, only for "production". Has your token higher limits? I don't mind using one or the other. README has been updated.

**Comment by abdullahdevrel** [comment]
@vincentbernat My apologies for the confusion. I was on PTO yesterday, so I wasn't able to respond earlier.

The rate limit for the access token used in this repo (`a26XXXXXXX7`) has been updated to allow up to 10 daily downloads. I don't think there will be any rate limit issues anymore, but please let me know if this happens again.

**Comment by saymonaraujo** [comment]
@vincentbernat can you provide a exemple on how to configure the token in the inlet service to use ipinfo ?
