### ISSUE TITLE
Support for ReplicatedMergeTree in ClickHouse

### ISSUE THREAD

**Issue by vincentbernat** [akvorado/akvorado#605]
Currently, tables are created as `MergeTree`, preventing the ability to use a clustered ClickHouse. To support `ReplicatedMergeTree`, we should:

- Accept several ClickHouse servers (both console and orchestrator)
- Switch to `ReplicatedMergeTree` when we have several ClickHouse servers
- Execute `CREATE`/`DROP` on all members of the cluster
- Execute `ALTER` only on one member

Optionally:

- Configure ClickHouse with a Zookeeper cluster
- Convert the existing `MergeTree` tables to `ReplicatedMergeTree` (this seems safe, see the [documentation](https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/replication#converting-from-mergetree-to-replicatedmergetree), there is little point of going the other direction)

**Comment by drMARTINS13** [comment]
I would also appreciate to run akvorado in some cluster mode.
It is not problem to prepare clickhouse and zookeeper cluster on another machine, but without support in akvorado it is useless.
Thank you

**Comment by netixx** [comment]
@vincentbernat any reason you mention that ALTER need to be done only on one member ?

It looks to me like this is covered by using "ON CLUSTER": https://clickhouse.com/docs/en/sql-reference/distributed-ddl

We were also looking at supporting clickhouse clustering in our setup, hopefully we can make a contribution in the next few weeks.

I think we would like to go one step further and support sharding as well (through distributed table): https://clickhouse.com/docs/en/engines/table-engines/special/distributed. Making it optional seems like a must because it requires an heavier setup on clickhouse side. But it brings the bonus on not relying on the size of one individual server for max scale.

**Comment by vincentbernat** [comment]
I don't remember. Maybe I misread the documentation or maybe ON CLUSTER was not available for CREATE in the past.

**Comment by vincentbernat** [comment]
I'll work on that next as we now need it too.
