### ISSUE TITLE
Add `SrcCity` and `DstCity`

### ISSUE THREAD

**Issue by vincentbernat** [akvorado/akvorado#62]
In addition to `SrcCountry` and `DstCountry`, it would be nice to be able to add `SrcCity` and `DstCity`.

However, this may a rabbit hole. The City Maxmind databases also contains:
- city
- continent
- country
- location (longitude/latitude)
- postal code
- subdivisions (many)

For each data, we may do something different:
- continent: get it from the country code using a dictionary lookup at query time
- city: use geoid
- country: use geoid or keep doing what we do
- location: consider city geoid is enough
- postal code: consider city geoid is enough
- subdivisions: use geoid

We could replace `SrcCountry` and `DstCountry` by `SrcGeoID` and `DstGeoID` and have a dictionary lookup during query to extract all the other fields we want (`SrcGeoContinent`, `SrcGeoCountry`, `SrcGeoRegion1`, `SrcGeoRegion2`, `SrcGeoCity`) using aliases (that's what is done for `PacketSize`, it's free to add more).

It would mean that we need access to GeoIP database from inlet (like currently) and from ClickHouse. To simplify things, we could consider moving all the geolocation stuff into ClickHouse. During ingestion, it would lookup the geoname ID. And during query, you get the remaining stuff.

AS numbers would stay in Akvorado as there are various ways we can get them and in the future, we want to configure their sources accurately.

- [ ] Move `inlet/geoip` to `common/geoip`, adapt `inlet` to use it (drop `LookupCountry`)
- [ ] Make `common/geoip` able to dump the provided database to CSV
- [ ] Make `orchestrator/clickhouse` expose this CSV to ClickHouse
- [ ] Add dictionary to ClickHouse, materialize a `SrcGeoID`/`DstGeoID` columns, drop the `SrcCountry`/`DstCountry`, add aliases for `SrcGeo*`/`DstGeo*` columns
- [ ] Make the new columns/aliases available from the console

It should be noted that using the city database will have an impact on the efficiency of the aggregation (it should be mentioned in documentation).

**Comment by netixx** [comment]
We had an idea similar to this in scope, but different in implementation.

The idea was to have everything done through a lookup in the networks dictionary inside clickhouse only.
We have already thought quite a lot about this, so here is how it would go in details:
- load one or more geoip database inside the orchestrator
- iter the database, and inject their contents into a trie
- iter the contents of the existing "networks", and put them into the same trie
- iter this converged trie, and fill the attributes that are undefined (eg. city) from the parent
- serve the results are networks.csv and have clickhouse load it
- change the columns to use clickhouse dict instead of geoip lookups

We call this converged-networks :)

The good features on this are:
- ability to override attributes from geoip with networks definition (eg. for internal networks, where geoip might not have the best info)
- no more CPU used in inlet for geoip lookups
- ability to combine multiple goeip database for most accurate results

**Comment by vincentbernat** [comment]
I am OK with the way you propose to implement. This should also retire the current way of doing this.

**Comment by vincentbernat** [comment]
It's implemented in 87a57bf.

**Comment by vincentbernat** [comment]
This one was not really implemented using geoid. Unfortunately, looking a bit more about it, not all databases have geonames associated to them. Moreover, there are 25 million geonames, too big for a ClickHouse dictionary. Also, there is one ID for the country, one ID for the city, so we can't just store one geoid. If we were to store only the city one, we could also get the country and the continent, but it is not like it would help a lot compared to a low cardinality column (there are ~250 countries). So, I don't think this is worth looking at geoids.
